package com.sieve.engine.update

import java.io.ByteArrayOutputStream
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.zip.CRC32
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/** Builds files shaped like the `yt-dlp` zipapp youtubedl-android runs (measured on the real 2025.11.12 file: 1122 entries, 23-byte shebang, relative offsets). */
internal object ZipappFixture {
    const val SHEBANG = "#!/usr/bin/env python3\n"

    /** `yt_dlp/version.py` as yt-dlp's devscripts/update-version.py writes it. */
    fun versionPy(version: String): String = """
        # Autogenerated by devscripts/update-version.py

        __version__ = '$version'

        RELEASE_GIT_HEAD = '335653be82d5ef999cfc2879d005397402eebec1'

        VARIANT = None

        UPDATE_HINT = None

        CHANNEL = 'stable'

        ORIGIN = 'yt-dlp/yt-dlp'

        _pkg_version = '$version'
    """.trimIndent() + "\n"

    /**
     * [shebang]: put the python shebang line in front (what the Makefile does with `cat`). The zip's own offsets stay relative to its start
     * unless [absoluteOffsets] (what `python -m zipapp` writes) shifts them by the prefix. [stored]: write version.py uncompressed.
     */
    fun build(
        version: String,
        shebang: Boolean = true,
        absoluteOffsets: Boolean = false,
        stored: Boolean = false,
        filler: Int = 300,
        versionPy: String = versionPy(version),
        comment: String? = null,
    ): ByteArray {
        val zip = ByteArrayOutputStream().also { bytes ->
            ZipOutputStream(bytes).use { z ->
                comment?.let { z.setComment(it) }
                fun put(name: String, body: ByteArray, store: Boolean = false) {
                    val e = ZipEntry(name)
                    if (store) {
                        e.method = ZipEntry.STORED
                        e.size = body.size.toLong()
                        e.compressedSize = body.size.toLong()
                        e.crc = CRC32().also { it.update(body) }.value
                    } else {
                        e.method = ZipEntry.DEFLATED
                    }
                    z.putNextEntry(e)
                    z.write(body)
                    z.closeEntry()
                }
                put("__main__.py", "import yt_dlp\nyt_dlp.main()\n".toByteArray())
                for (i in 0 until filler) put("yt_dlp/extractor/site$i.py", "class Site${i}IE:\n    pass  # $i\n".repeat(20).toByteArray())
                put("yt_dlp/version.py", versionPy.toByteArray(), store = stored)
                put("yt_dlp/__init__.py", "__version__ = 'not this one'\n".toByteArray())
            }
        }.toByteArray()
        val prefix = if (shebang) SHEBANG.toByteArray() else ByteArray(0)
        if (absoluteOffsets) shiftOffsets(zip, prefix.size)
        return prefix + zip
    }

    /** Writes a yt-dlp-shaped file for [version] to [file] (replacing it), the way the library's updater does. */
    fun write(file: File, version: String): File = file.apply { parentFile?.mkdirs(); writeBytes(build(version)) }

    /** Adds [by] to every local-header offset in the central directory and to the directory's own offset (no zip comment assumed unless found). */
    private fun shiftOffsets(zip: ByteArray, by: Int) {
        val b = ByteBuffer.wrap(zip).order(ByteOrder.LITTLE_ENDIAN)
        var eocd = zip.size - 22
        while (b.getInt(eocd) != 0x06054b50) eocd--
        val cenOffset = b.getInt(eocd + 16)
        var p = cenOffset
        while (p < eocd && b.getInt(p) == 0x02014b50) {
            b.putInt(p + 42, b.getInt(p + 42) + by)
            p += 46 + (b.getShort(p + 28).toInt() and 0xFFFF) + (b.getShort(p + 30).toInt() and 0xFFFF) + (b.getShort(p + 32).toInt() and 0xFFFF)
        }
        b.putInt(eocd + 16, cenOffset + by)
    }
}
