package com.sieve.app.settings

import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File
import java.io.IOException
import java.io.InputStream
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertIs
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

class CookiesFileTest {
    private val sid = ".youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tabc"
    private val httpOnly = "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1893456000\t__Secure-1PSID\tdef"
    private val emptyValue = ".example.com\tTRUE\t/\tFALSE\t0\tflag\t"   // empty value keeps its trailing tab

    @Test fun countsCookieLinesIncludingHttpOnlyAndEmptyValues() {
        val c = CookiesFile.clean("# Netscape HTTP Cookie File\n$sid\n$httpOnly\n$emptyValue\n")
        assertEquals(3, c.count)
        assertTrue(c.text.contains(emptyValue))                               // the trailing tab survived
        assertTrue(c.text.startsWith("# Netscape HTTP Cookie File\n"))
    }

    @Test fun addsTheHeaderYtDlpRequires() {
        val c = CookiesFile.clean("$sid\n")
        assertEquals(1, c.count)
        assertEquals("# Netscape HTTP Cookie File\n$sid\n", c.text)
        // an unrelated first comment is not the magic line either
        assertTrue(CookiesFile.clean("# generated by an extension\n$sid\n").text.startsWith("# Netscape HTTP Cookie File\n"))
    }

    @Test fun acceptsTheShortHeaderWithoutDuplicatingIt() {
        val c = CookiesFile.clean("# HTTP Cookie File\n$sid\n")
        assertEquals("# HTTP Cookie File\n$sid\n", c.text)
    }

    @Test fun normalizesBomAndWindowsLineEndings() {
        val c = CookiesFile.clean("\uFEFF# Netscape HTTP Cookie File\r\n$sid\r\n$httpOnly\r\n")
        assertEquals(2, c.count)
        assertFalse(c.text.contains("\r"))
        assertFalse(c.text.contains("\uFEFF"))
    }

    @Test fun dropsMalformedAndBlankLinesSoOneBadLineCantBreakEveryDownload() {
        val c = CookiesFile.clean("# Netscape HTTP Cookie File\n\n$sid\nthis line is junk\n.a.com\tTRUE\t/\n$httpOnly\n")
        assertEquals(2, c.count)
        assertFalse(c.text.contains("junk"))
        assertFalse(c.text.contains(".a.com"))
        assertFalse(c.text.contains("\n\n"))
    }

    @Test fun nonCookieContentHasNoCookies() {
        assertEquals(0, CookiesFile.clean("").count)
        assertEquals(0, CookiesFile.clean("buy milk").count)
        assertEquals(0, CookiesFile.clean("{\"cookies\": []}").count)
        assertEquals(0, CookiesFile.clean("# Netscape HTTP Cookie File\n# nothing here\n").count)
    }

    @Test fun ageLabelsAndThresholdsMatchTheDesktopChip() {
        assertEquals("< 1 day old", CookiesFile.ageLabel(0.4))
        assertEquals("1 day old", CookiesFile.ageLabel(1.5))
        assertEquals("12 days old", CookiesFile.ageLabel(12.9))
        assertEquals("31 days old \u00B7 stale", CookiesFile.ageLabel(31.2))
        assertEquals("120 days old \u00B7 very stale", CookiesFile.ageLabel(120.0))
        assertEquals(CookieAge.FRESH, CookieAge.of(30.0))
        assertEquals(CookieAge.STALE, CookieAge.of(30.1))
        assertEquals(CookieAge.STALE, CookieAge.of(90.0))
        assertEquals(CookieAge.VERY_STALE, CookieAge.of(90.1))
        assertNull(CookiesFile.warning(5.0))
        assertNotNull(CookiesFile.warning(45.0))
        assertTrue(CookiesFile.warning(120.0)!!.startsWith("Very old"))
    }

    @Test fun statusLineCountsCookies() {
        assertEquals("cookies.txt loaded (1 cookie)", CookiesFile.statusLine(CookiesInfo(1, 0)))
        assertEquals("cookies.txt loaded (42 cookies)", CookiesFile.statusLine(CookiesInfo(42, 0)))
    }

    @Test fun ageNeverGoesNegative() {
        assertEquals(0.0, CookiesInfo(1, modifiedAt = 5_000).ageDays(now = 1_000))
        assertEquals(2.0, CookiesInfo(1, modifiedAt = 0).ageDays(now = 2 * CookiesInfo.DAY_MS))
    }
}

class CookiesStoreTest {
    @get:Rule val tmp = TemporaryFolder()

    private val sid = ".youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tabc"
    private val docs = mutableMapOf<String, ByteArray>()
    private val modified = mutableMapOf<String, Long>()

    private fun store(dir: File = File(tmp.root, "files")) =
        CookiesStore(dir, open = { docs[it]?.inputStream() }, lastModifiedOf = { modified[it] })

    @Test fun importCopiesACleanedFileIntoThePrivateDir() {
        docs["content://p/1"] = "$sid\r\n".toByteArray()
        val s = store()
        val r = s.importFrom("content://p/1")

        assertIs<CookiesStore.Result.Imported>(r)
        assertEquals(1, r.info.count)
        assertEquals(File(tmp.root, "files/cookies.txt"), s.file)
        assertEquals("# Netscape HTTP Cookie File\n$sid\n", s.file.readText())
        assertFalse(File(tmp.root, "files/cookies.txt.tmp").exists())
    }

    @Test fun theCopyKeepsTheDocumentsOwnModifiedTimeSoTheAgeWarningIsHonest() {
        docs["content://p/1"] = "$sid\n".toByteArray()
        val tenDaysAgo = System.currentTimeMillis() - 10 * CookiesInfo.DAY_MS
        modified["content://p/1"] = tenDaysAgo
        val s = store()
        val r = s.importFrom("content://p/1") as CookiesStore.Result.Imported

        assertTrue(kotlin.math.abs(s.file.lastModified() - tenDaysAgo) < 2_000)    // filesystem mtime granularity
        assertTrue(r.info.ageDays(System.currentTimeMillis()) in 9.9..10.1)
    }

    @Test fun anUnknownModifiedTimeFallsBackToNow() {
        docs["content://p/1"] = "$sid\n".toByteArray()
        val r = store().importFrom("content://p/1") as CookiesStore.Result.Imported
        assertTrue(r.info.ageDays(System.currentTimeMillis()) < 0.01)
    }

    @Test fun aReplaceOverwritesThePreviousFile() {
        val s = store()
        docs["content://p/1"] = "$sid\n".toByteArray()
        docs["content://p/2"] = ".b.com\tTRUE\t/\tTRUE\t0\tB\t2\n.c.com\tTRUE\t/\tTRUE\t0\tC\t3\n".toByteArray()
        s.importFrom("content://p/1")
        val r = s.importFrom("content://p/2") as CookiesStore.Result.Imported
        assertEquals(2, r.info.count)
        assertFalse(s.file.readText().contains("youtube"))
    }

    @Test fun aNonCookiesFileIsRejectedAndLeavesTheOldOneAlone() {
        val s = store()
        docs["content://p/1"] = "$sid\n".toByteArray()
        docs["content://p/2"] = "hello".toByteArray()
        s.importFrom("content://p/1")
        assertEquals(CookiesStore.Result.NotCookies, s.importFrom("content://p/2"))
        assertTrue(s.file.readText().contains("SID"))
    }

    @Test fun anUnreadableDocumentIsReported() {
        assertEquals(CookiesStore.Result.Unreadable, store().importFrom("content://p/missing"))
        val throwing = CookiesStore(File(tmp.root, "x"), open = { throw IOException("revoked") })
        assertEquals(CookiesStore.Result.Unreadable, throwing.importFrom("content://p/1"))
        val denied = CookiesStore(File(tmp.root, "y"), open = { throw SecurityException("no grant") })
        assertEquals(CookiesStore.Result.Unreadable, denied.importFrom("content://p/1"))
    }

    @Test fun aHugeFileIsNotACookiesTxt() {
        val big = object : InputStream() {
            var left = CookiesStore.MAX_BYTES + 1024L
            override fun read(): Int = if (left-- > 0) 'a'.code else -1
            override fun read(b: ByteArray, off: Int, len: Int): Int {
                if (left <= 0) return -1
                val n = minOf(len.toLong(), left).toInt(); java.util.Arrays.fill(b, off, off + n, 'a'.code.toByte()); left -= n; return n
            }
        }
        assertEquals(CookiesStore.Result.Unreadable, CookiesStore(File(tmp.root, "z"), open = { big }).importFrom("content://p/big"))
    }

    @Test fun infoReflectsTheFileAndRemoveDeletesIt() {
        val s = store()
        assertNull(s.info())
        docs["content://p/1"] = "$sid\n".toByteArray()
        s.importFrom("content://p/1")
        assertEquals(1, s.info()!!.count)
        s.remove()
        assertNull(s.info())
        assertFalse(s.file.exists())
        s.remove()                                                       // removing twice is harmless
    }
}
